export const ACTION_INCREASE = "ACTION_INCREASE"
export const ACTION_DECREASE = "ACTION_DECREASE"
//Product

export const ACTION_INSERT_PRODUCT = "ACTION_INSERT_PRODUCT"
export const ACTION_DELETE_PRODUCT = "ACTION_DELETE_PRODUCT"
export const ACTION_UPDATE_PRODUCT = "ACTION_UPDATE_PRODUCT"
